#' Synthetic sample sales panel
#'
#' A small, reproducible retail sales panel generated by [make_sample_sales()],
#' schema-compatible with the Favorita `train.csv`. It deliberately contains a few
#' data-quality defects (missing values, duplicates, negatives and a multi-day
#' gap) so that the validation and cleaning functions can be demonstrated.
#'
#' @format A tibble with the columns:
#' \describe{
#'   \item{id}{Integer row identifier.}
#'   \item{date}{Date of the observation.}
#'   \item{store_nbr}{Integer store number.}
#'   \item{family}{Product family (character).}
#'   \item{sales}{Daily sales (double).}
#'   \item{onpromotion}{Promotion flag (integer 0/1).}
#' }
#' @source Generated with `make_sample_sales(n_stores = 6, n_families = 4,
#'   start = "2015-01-01", days = 365, seed = 42)`.
#' @seealso [sample_stores], [make_sample_sales()]
"sample_sales"

#' Synthetic sample store metadata
#'
#' Store-level metadata accompanying [sample_sales], schema-compatible with the
#' Favorita `stores.csv`.
#'
#' @format A tibble with the columns:
#' \describe{
#'   \item{store_nbr}{Integer store number (join key to [sample_sales]).}
#'   \item{city}{City name.}
#'   \item{state}{State / province name.}
#'   \item{type}{Store type (one of A, B, C, D, E).}
#'   \item{cluster}{Integer store cluster.}
#' }
#' @source Generated with `make_sample_sales()` (see the `stores` element).
#' @seealso [sample_sales]
"sample_stores"
